Corrected apps/code/*.hu.i18n hungarian text files
Omega-Numworks/Omega pull request #425
Opened 2020-11-15 17:05 UTC by lapingenieur

2nd try with more modifications...
Also changed "monoton**ic**" to "mononton**e**" in apps/code/catalog.fr.i18n (think it's a spelling mistake)

2020-11-15 17:08 UTC, lapingenieur commented
je sais d'ou vient l'erreur je vais la corriger tout de suite :)

2020-11-15 17:20 UTC, lapingenieur commented
The `ε` character seems to have some problems...

2020-11-15 17:24 UTC, quentinguidee commented
> The `ε` character seems to have some problems...

The characters you can use are listed here: https://github.com/Omega-Numworks/Omega/blob/omega-master/kandinsky/fonts/code_points.h

2020-11-15 17:43 UTC, lapingenieur commented
I don't understand why this test (Metrics / binary-size (pull_request)) fails...

2020-11-15 17:46 UTC, RedGl0w commented
> I don't understand why this test (Metrics / binary-size (pull_request)) fails...

See https://github.com/numworks/epsilon/pull/1701

2020-11-18 18:27 UTC, Gegenter commented on apps/code/base.hu.i18n
> +AddScript = "Script hozzadás"
```suggestion
AddScript = "Script hozzadása"

```

2020-11-18 18:27 UTC, Gegenter commented on apps/code/base.hu.i18n
> +BuiltinsAndKeywords = "Beépítet fonkciók és szókincs"
```suggestion
BuiltinsAndKeywords = "Beépítet funkciók és szókincs"

```

2020-11-18 18:27 UTC, Gegenter commented on apps/code/base.hu.i18n
> +ScriptSize = "Script hossza"
```suggestion
ScriptSize = "Script mérete"

```

2020-11-18 18:29 UTC, Gegenter commented on apps/code/catalog.hu.i18n
> +PythonTurtleGoto = "Manjen a (x,y) koordinátákra"
```suggestion
PythonTurtleGoto = "Menjen a (x,y) koordinátákra"

```

2020-11-18 18:30 UTC, Gegenter requested changes
Only 3 things to correct otherwise good job!!.

2020-11-18 19:51 UTC, lapingenieur reviewed
More hungarian changes thanks to @Gegenter

2020-11-18 19:57 UTC, lapingenieur commented on apps/code/catalog.hu.i18n
> +
Is this line that messes up the test ?

2021-02-08 19:38 UTC, Gegenter requested changes
That's about it, good job, only a couple of errors 👍 

-Gegenter

2021-02-08 19:38 UTC, Gegenter commented on apps/code/base.hu.i18n
> +FunctionsAndVariables = "Fonktiók és változók"
This is wrong, the other one was correct, "Függvények" is the correct term.

2021-02-08 19:38 UTC, Gegenter commented on apps/on_boarding/base.hu.i18n
> +UpdateMessage3 = "Töltje laa weboldalunkról az utolso verziót"
Should be "Töltse le a weboldalunkról az utolsó verziót"

2021-02-08 19:38 UTC, Gegenter commented on apps/regression/base.hu.i18n
> +Proportional = "Általános"
Proportional is technically "Arányos" in Hungarian altough when speaking about a functions and such it should be "egyenes arányosság" but i think "Arányos" is enough and everyone understands.

2021-02-08 19:38 UTC, Gegenter commented on apps/regression/base.hu.i18n
> +DataNotSuitableForRegression = "Azek az adatok nem megfelelö ehhez a regressziós modellhez"
"Ezek az adatok nem megfelelőek ehhez a regressziós modellhez" <-- this is correct

2021-02-08 19:38 UTC, Gegenter commented on apps/settings/base.hu.i18n
> +About = "Apropó"
"Egyéb" is more "professional" i would not use "apropó" here

2021-02-08 19:38 UTC, Gegenter commented on apps/shared.hu.i18n
> +DefaultSetting = "Alapállítások"
"Alapbeállítások" was good, i dunno why it was changed, maybe an error.

2021-02-08 19:38 UTC, Gegenter commented on apps/shared.hu.i18n
> +ExitExamMode1 = "Kilépni a vizsga "
"Kilépés" was the correct one gramatically,

2021-02-08 19:38 UTC, Gegenter commented on apps/shared.hu.i18n
> +LowBattery = "Majdnem kimerült az elem"
"Alacsony töltöttség" is more professional and shorter, I think we should go with that.

2021-02-08 19:38 UTC, Gegenter commented on apps/shared.hu.i18n
> +StorageMemoryFull2 = "Törlöljön adatokat és próbálkozzon újra."
"Töröljön" is the correct form.

2021-02-08 19:38 UTC, Gegenter commented on apps/shared.hu.i18n
> +Developers = "Kifejlesztök"
Although we say "kifejlesztők" its generally meant for vaccines and such. "Fejlesztők" is the correct term here.

2021-02-08 19:38 UTC, Gegenter commented on apps/solver/base.hu.i18n
> +AddEquation = "Egyenlet hozzáadás"
"hozzáadása"

2021-02-08 19:38 UTC, Gegenter commented on apps/solver/base.hu.i18n
> +RequireEquation = "A bemenetnek csak egyenlet lehet"
We can write "A bemenet csak egyenlet lehet" or " A bemenetnek egyenletnek kell lennie" both are correct.

2021-02-08 19:38 UTC, Gegenter commented on apps/solver/base.hu.i18n
> +InfiniteNumberOfSolutions = "Végtelen menyi megoldások léteznek"
Once again the other one was good, the changed one makes no sense grammatically. We should use " Végtelen számú megoldás létezik"

2021-02-08 19:38 UTC, Gegenter commented on apps/solver/base.hu.i18n
> +OnlyFirstSolutionsDisplayed0 = "Csak a 10 elsö megoldások"
"Csak az első 10 megoldás"

2021-02-08 19:38 UTC, Gegenter commented on apps/solver/base.hu.i18n
> +OnlyFirstSolutionsDisplayed1 = "jelennek meg"
"Jelenjen meg"

2021-02-08 19:38 UTC, Gegenter commented on apps/variables.hu.i18n
> +Functions = "Funciók"
Függvény is correct "Funciók" doesnt exist.

2021-02-08 19:38 UTC, Gegenter commented on apps/variables.hu.i18n
> +EmptyFunctionBox0 = "Nincs meghatározott funkció."
Although grammatically correct, i would change funkció to függvény.

2021-02-08 19:38 UTC, Gegenter commented on apps/variables.hu.i18n
> +EmptyFunctionBox1 = "Funkció meghatározásához írja be:"
Függvény

2021-02-08 19:38 UTC, Gegenter commented on apps/variables.hu.i18n
> +EmptyFunctionBox2 = "A funkció neve tartalmazhat:"
Függvény

2021-02-08 20:16 UTC, lapingenieur reviewed
If I did right @Gegenter 's changes should be added to this pr

2021-02-10 18:13 UTC, merged